spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ${SMTP_EMAIL}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${SMTP_PASSWORD}

  mvc:
    throw-exception-if-no-handler-found: 'true'
  web:
    resources:
      add-mappings: 'false'

  security:
    oauth2:
      client:
        registration:
          google:
            # 발급 받은 Client ID
            client-id: ${google-client-id}
            # 발급 받은 Client Secret
            client-secret: ${google-client-secret}
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
          kakao:
            client-id: ${kakao-client-id} # 발급 받은 Client ID
            client-secret: ${kakao-client-secret} # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              #              - profile_nickname
              #              - profile_image
              - account_email
            #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao

          naver:
            client-id: ${naver-client-id} # 발급 받은 Client ID
            client-secret: ${naver-client-secret} # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              #              - name
              - email
            #              - email_address    # 검수 후 사용
            #              - profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정



  redis:
    host: localhost
    port: ${REDIS_PORT}
  application:
    name: be
  datasource:
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  docker:
    compose:
      lifecycle-management: start-and-stop
jwt:
  secret: ${JWT_SECRET}
cors:
  allowed-origin: https://${DOMAIN}
server:
  port: '8080'
