version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql

  redis-dev:
    container_name: redis-dev-container
    image: redis
    volumes:
      - redis-dev-volume:/data
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    restart: always

volumes:
  mysql-volume:
  redis-dev-volume: